name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # или твоя основная ветка, если не main

# Устанавливает права GITHUB_TOKEN, чтобы разрешить развёртывание на GitHub Pages
permissions:
  contents: read # Мы разрешаем читать контент из нашего репозитория
  pages: write # разрешаем перезаписывать github page
  id-token: write # Разрешаем использовать GITHUB_TOKEN

env:
  PUBLIC_PATH: /github_actions/

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'  # можно указать твою версию Node

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          force_orphan: true
